version: '3.8'

services:
  # Redis 服务
  redis:
    image: redis:7-alpine
    container_name: rox-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-K9mP3xQ7nR2w}
    volumes:
      - ./redis-data:/data
    networks:
      - rox-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  # API 服务
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: rox-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - rox-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # 前端服务
  web2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rox-web2
    ports:
      - "3000:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - rox-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - ./roxdb.games_nginx/roxdb.games_bundle.crt:/usr/share/nginx/roxdb.games_bundle.crt
      - ./roxdb.games_nginx/roxdb.games.key:/usr/share/nginx/roxdb.games.key
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=rox-web2"
      - "com.docker.compose.service=web2"

networks:
  rox-network:
    driver: bridge
    name: rox-network